version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: 00xctf-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: 00xctf-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  #frontend:
  #   build: ./frontend
#    container_name: 00xctf-frontend
#    restart: always
#    ports:
#      - "5173:5173"
#   depends_on:
#     - backend

volumes:
  postgres_data:
